### ISSUE TITLE
Run catelog insertion script

### ISSUE THREAD

**Issue by jwdenne** [gilbertconsult/webtest#1]
Hey Keith,

Could you please show me how to implement the new script for our flyer page builds? Setting up the indesign templates(with associated #'s and running the script to populate from excel doc.)? I've tried but keep getting error message. I'm doing something wrong. Thanks!

**Comment by gilbertconsult** [comment]
@jwdenne Want to do a screen share session tomorrow afternoon? I'm free between 2 and 5pm Central.

**Comment by jwdenne** [comment]
That would be great, thank you! 2:30 Central will work for us. Could you please also invite:  jmarcus@ollies.us and polder@ollies.us

**Comment by gilbertconsult** [comment]
OK, great. Will send an invite later this afternoon.

**Comment by jwdenne** [comment]
Thanks Keith! Appreciate it.
